"""
Deco2025_CHARM_SC/examples/run_fc_model.py
----------------------------------
Reproduces FCmodel.m from Deco et al. (2025).

Compares FC generated by random-walk simulations (HARM and CHARM-SC)
against empirical FC computed from real BOLD data.

Original MATLAB               →   This file
------------------------------    --------------------------------
load schaefercog.mat          →   DL.get_parcellation().get_CoGs()
load hcp_REST_LR_schaefer1000 →   DL (HCP DataLoader)
filtfilt + corrcoef           →   BandPassFilter + NeuroNumba FC observable
%% HARM SC + %% CHARM SC       →   HARM, CHARM_SC (geometry models)
inner simulation loop         →   BOLDGenerator.simulate_fc()
corrcoef(FCemp, FCsim)        →   scipy.stats.pearsonr on lower triangles
boxplot + ranksum              →   matplotlib violinplot + scipy.stats.ranksums

Demo parameters (reduced from paper for speed):
    NSUB      = 1003  → n_subjects = 10
    NTRIALS   = 1000  → n_trials   = 20
    NREP      = 200   → n_reps     = 10
    T_sim     = 1000  → n_timesteps = 200
    N         = 1000  (unchanged — determined by parcellation)

Usage
-----
    python examples/run_fc_model.py

Output
------
    _Data_Produced/results_fc_model.mat
    _Data_Produced/fc_model_corr.pdf
    _Data_Produced/fc_model_mse.pdf
"""

import os
import numpy as np
import scipy.io as sio
from scipy import stats
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ── CHARMsc library ───────────────────────────────────────────────────────────
from geometry import HARM, CHARM_SC
from simulation.bold_generator import BOLDGenerator

# ── NeuroNumba ────────────────────────────────────────────────────────────────
from neuronumba.observables.fc import FC as _FCObservable
from neuronumba.tools.filters import BandPassFilter

# ── Your existing data infrastructure ────────────────────────────────────────
from DataLoaders.HCP_Schaefer2018 import HCP


# =============================================================================
# Parameters
# =============================================================================

# Demo values (reduced from paper for speed).
# To reproduce paper results: n_subjects=1003, n_trials=1000, n_reps=200,
#                             n_timesteps=1000
N_SUBJECTS   = 10    # paper: 1003
N_TRIALS     = 500  # paper: 1000
N_REPS       = 200    # paper: 200
N_TIMESTEPS  = 1000  # paper: 1000

EPSILON      = 1400.0
T_HORIZON    = 2
DIFF_STEPS   = 50
OUTPUT_DIR   = '_Data_Produced'

# Parcels 554 and 907 (0-indexed) correspond to MATLAB parcels 555
# and 908 (1-indexed). These two parcels have NaN entries in the
# Schaefer 1000 atlas HCP data and must be excluded from comparisons.
# Assumption: specific to the Schaefer 1000 parcellation with this
# particular HCP dataset.
EXCLUDE_PARCELS = [554, 907]   # Schaefer1000 NaN parcels (0-indexed)

# Window size for rolling correlation analysis (matches FCmodel.m: NW=10)
NW = 10


# =============================================================================
# Step 1: Compute empirical FC from real BOLD
# =============================================================================
def clean_data(X, id):
    bad_regions = np.where(np.all(np.isnan(X), axis=1))[0]
    X_clean = np.delete(X, bad_regions, axis=0)
    print(f"Subject {id}: {len(bad_regions)} parcels removed due to missing time series")
    return X_clean


# =============================================================================
# Step 1: Compute empirical FC from real BOLD
# =============================================================================

def compute_empirical_fc(DL: HCP, n_subjects: int) -> np.ndarray:
    """
    Compute the group-average empirical FC from filtered BOLD timeseries.

    Matches the MATLAB pipeline:
        for sub=1:NSUB
            filtfilt(bfilt, afilt, ts)
            FCemp2(sub,:,:) = corrcoef(tfilt')
        FCemp = nanmean(FCemp2)

    Parameters
    ----------
    DL         : HCP data loader
    n_subjects : number of subjects to include

    Returns
    -------
    FC_emp : np.ndarray, shape (N, N)
        Group-average empirical FC matrix.
    """
    print(f"\nComputing empirical FC from {n_subjects} subjects...")

    bpf = BandPassFilter(
        k=2,
        tr=DL.TR() * 1000.0,   # seconds → milliseconds (BandPassFilter expects ms)
        flp=0.008,
        fhi=0.08,
        remove_artifacts=False,
        apply_demean=True,
        apply_detrend=True,
    )

    subjects = DL.get_groupSubjects('REST1')[:n_subjects]
    N        = DL.N()
    excl = len(EXCLUDE_PARCELS)
    FC_sum   = np.zeros((N-excl, N-excl))
    fc_obs   = _FCObservable()
    n_valid  = 0

    for subj in subjects:
        ts = DL.get_subjectData(subj)[subj]['timeseries']   # (N, T)
        ts = clean_data(ts, subj)

        # BandPassFilter expects (T, N) — transpose in, transpose out
        ts_filt = bpf.filter(ts.T).T                    # (N, T)

        # Trim 50 timepoints from each end (MATLAB: tfilt(50:end-50))
        ts_trim = ts_filt[:, 49: -50]                       # (N, T')

        # FC observable expects (T, N)
        result   = fc_obs.from_fmri(ts_trim.T)
        FC_sum  += result['FC']
        n_valid += 1

    FC_emp = FC_sum / max(n_valid, 1)
    print(f"  Empirical FC computed from {n_valid} valid subjects.")
    return FC_emp


# =============================================================================
# Step 2: Fit geometry and run simulations
# =============================================================================

def run_simulations(
    coords:      np.ndarray,
    n_trials:    int,
    n_reps:      int,
    n_timesteps: int,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Fit HARM and CHARM-SC, then simulate FC via random walks.

    Returns
    -------
    FC_reps_harm  : np.ndarray, shape (n_reps, N, N)
    FC_reps_charm : np.ndarray, shape (n_reps, N, N)
    """
    print("\nFitting geometry models...")
    harm  = HARM(epsilon=EPSILON, t_horizon=T_HORIZON,
                 diffusion_steps=DIFF_STEPS)
    charm = CHARM_SC(epsilon=EPSILON, t_horizon=T_HORIZON,
                     diffusion_steps=DIFF_STEPS)
    harm.fit(coords)
    charm.fit(coords)

    print(f"\nRunning HARM simulations "
          f"({n_reps} reps × {n_trials} trials × {n_timesteps} steps)...")
    gen_harm = BOLDGenerator(
        P            = harm.diffusion_matrix,
        n_timesteps  = n_timesteps,
        random_state = 42,
    )
    FC_reps_harm = gen_harm.simulate_fc(
        n_trials       = n_trials,
        n_repetitions  = n_reps,
        use_vectorised = True,
    )

    print(f"\nRunning CHARM-SC simulations "
          f"({n_reps} reps × {n_trials} trials × {n_timesteps} steps)...")
    gen_charm = BOLDGenerator(
        P            = charm.diffusion_matrix,
        n_timesteps  = n_timesteps,
        random_state = 42,
    )
    FC_reps_charm = gen_charm.simulate_fc(
        n_trials       = n_trials,
        n_repetitions  = n_reps,
        use_vectorised = True,
    )

    return FC_reps_harm, FC_reps_charm


# =============================================================================
# Step 3: Compare simulated FC against empirical FC
# =============================================================================

def compare_fc(
    FC_emp:        np.ndarray,
    FC_reps_harm:  np.ndarray,
    FC_reps_charm: np.ndarray,
    nw:            int = NW,
) -> dict:
    """
    Compute rolling-window Pearson r and MSE between simulated and
    empirical FC, matching FCmodel.m's rolling average loop:

        for i=1:NW:200
            FCs  = mean(FCsim2(i:i+NW-1,:,:))
            FCsC = mean(FCsimC2(i:i+NW-1,:,:))
            corrFCempHARM(nn) = corrcoef(FCemp, FCs)
            ...

    Parameters
    ----------
    FC_emp        : (N, N)
    FC_reps_harm  : (n_reps, N, N)
    FC_reps_charm : (n_reps, N, N)
    nw            : rolling window size

    Returns
    -------
    dict with arrays of length n_windows:
        'corr_harm', 'corr_charm', 'mse_harm', 'mse_charm'
        'corr_gbc_harm', 'corr_gbc_charm', 'mse_gbc_harm', 'mse_gbc_charm'
    """
    N       = FC_emp.shape[0]
    n_reps  = FC_reps_harm.shape[0]
    n_win   = max(1, n_reps // nw)

    # Lower-triangle indices (off-diagonal FC edges)
    i_lt, j_lt = np.tril_indices(N, k=-1)
    fc_emp_vec  = FC_emp[i_lt, j_lt]

    # GBC (global brain connectivity) = mean FC per parcel
    gbc_emp = FC_emp.mean(axis=0)   # (N,)

    metrics = {k: np.zeros(n_win) for k in [
        'corr_harm', 'corr_charm', 'mse_harm', 'mse_charm',
        'corr_gbc_harm', 'corr_gbc_charm', 'mse_gbc_harm', 'mse_gbc_charm',
    ]}

    for nn, i in enumerate(range(0, n_win * nw, nw)):
        end  = min(i + nw, n_reps)
        FCs  = FC_reps_harm[i:end].mean(axis=0)    # (N, N)
        FCsC = FC_reps_charm[i:end].mean(axis=0)   # (N, N)

        # FC lower-triangle correlation and MSE
        fcs_vec  = FCs[i_lt, j_lt]
        fcsc_vec = FCsC[i_lt, j_lt]
        metrics['corr_harm'][nn],  _  = stats.pearsonr(fc_emp_vec, fcs_vec)
        metrics['corr_charm'][nn], _  = stats.pearsonr(fc_emp_vec, fcsc_vec)
        metrics['mse_harm'][nn]   = np.nanmean((fc_emp_vec - fcs_vec)  ** 2)
        metrics['mse_charm'][nn]  = np.nanmean((fc_emp_vec - fcsc_vec) ** 2)

        # GBC correlation and MSE
        gbc_s  = FCs.mean(axis=0)
        gbc_sc = FCsC.mean(axis=0)
        metrics['corr_gbc_harm'][nn],  _ = stats.pearsonr(gbc_emp, gbc_s)
        metrics['corr_gbc_charm'][nn], _ = stats.pearsonr(gbc_emp, gbc_sc)
        metrics['mse_gbc_harm'][nn]  = np.nanmean((gbc_emp - gbc_s)  ** 2)
        metrics['mse_gbc_charm'][nn] = np.nanmean((gbc_emp - gbc_sc) ** 2)

    return metrics


# =============================================================================
# Plotting
# =============================================================================

def plot_results(metrics: dict, output_dir: str) -> None:
    """
    Produce violin plots for FC correlation and MSE, matching FCmodel.m
    figures 1-4.
    """
    os.makedirs(output_dir, exist_ok=True)

    plot_specs = [
        ('corr_harm',    'corr_charm',    'Pearson r (FC)',       'fc_corr',  False),
        ('mse_harm',     'mse_charm',     'MSE (FC)',             'fc_mse',   True),
        ('corr_gbc_harm','corr_gbc_charm','Pearson r (GBC)',      'gbc_corr', False),
        ('mse_gbc_harm', 'mse_gbc_charm', 'MSE (GBC)',            'gbc_mse',  True),
    ]

    for harm_key, charm_key, ylabel, fname, lower_is_better in plot_specs:
        harm_vals  = metrics[harm_key]
        charm_vals = metrics[charm_key]
        stat, p    = stats.ranksums(harm_vals, charm_vals)
        stars = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'

        fig, ax = plt.subplots(figsize=(5, 5))
        vp = ax.violinplot([harm_vals, charm_vals], positions=[1, 2],
                           widths=0.6, showmedians=True, showextrema=True)
        vp['bodies'][0].set_facecolor('#5B9BD5')
        vp['bodies'][1].set_facecolor('#F4A261')
        for body in vp['bodies']:
            body.set_alpha(0.7); body.set_edgecolor('white')
        for part in ('cmedians', 'cmins', 'cmaxes', 'cbars'):
            vp[part].set_color('0.3')

        rng = np.random.default_rng(0)
        for i, vals in enumerate([harm_vals, charm_vals], start=1):
            jitter = rng.uniform(-0.08, 0.08, size=len(vals))
            ax.scatter(i + jitter, vals, s=30, alpha=0.8,
                       color=['#1F5FAC', '#C1440E'][i - 1],
                       edgecolors='white', linewidths=0.4, zorder=3)

        y_max = max(np.max(harm_vals), np.max(charm_vals))
        y_sig = y_max + 0.05 * abs(y_max)
        ax.plot([1, 2], [y_sig, y_sig], 'k-', linewidth=1.0)
        ax.text(1.5, y_sig, stars, ha='center', va='bottom', fontsize=11)

        ax.set_xticks([1, 2])
        ax.set_xticklabels(['HARM', 'CHARM-SC'], fontsize=11)
        ax.set_ylabel(ylabel, fontsize=10)
        ax.set_title(
            f'FC Model: {ylabel}\n'
            f'(n_reps={len(harm_vals)}, Wilcoxon p={p:.3f})',
            fontsize=10,
        )
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.grid(axis='y', alpha=0.2, linestyle=':')

        path = f'{output_dir}/fc_model_{fname}.pdf'
        fig.savefig(path, bbox_inches='tight', dpi=150)
        fig.savefig(path.replace('.pdf', '.png'), bbox_inches='tight', dpi=150)
        plt.close(fig)
        print(f"  Saved: {path}")


# =============================================================================
# Main
# =============================================================================

def main():
    print("=" * 60)
    print("FC Model: HARM vs CHARM-SC random-walk FC generation")
    print("=" * 60)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # 1. Load data
    print("\nLoading HCP Schaefer1000 data...")
    DL     = HCP(SchaeferSize=1000)
    coords = DL.get_parcellation().get_CoGs()  # (N, 3)
    # OK, but the Schaefer parcellation at N=1000 has a couple of rows of NaNs
    first = list(DL.get_classification().keys())[0]
    ts = DL.get_subjectData(first)[first]['timeseries']
    coords = coords[~np.isnan(ts).any(axis=1)]

    # 2. Empirical FC
    FC_emp = compute_empirical_fc(DL, N_SUBJECTS)

    # 3. Fit geometry + simulate
    FC_reps_harm, FC_reps_charm = run_simulations(
        coords, N_TRIALS, N_REPS, N_TIMESTEPS,
    )

    # Overall simulated FC (average over all reps)
    FC_sim  = FC_reps_harm.mean(axis=0)
    FC_simC = FC_reps_charm.mean(axis=0)

    # Quick summary correlation
    N       = FC_emp.shape[0]
    i_lt, j_lt = np.tril_indices(N, k=-1)
    r_harm,  _ = stats.pearsonr(FC_emp[i_lt, j_lt], FC_sim[i_lt, j_lt])
    r_charm, _ = stats.pearsonr(FC_emp[i_lt, j_lt], FC_simC[i_lt, j_lt])
    print(f"\n  FC correlation  HARM   vs empirical: r = {r_harm:.4f}")
    print(f"  FC correlation  CHARM  vs empirical: r = {r_charm:.4f}")

    # 4. Rolling-window metrics
    print("\nComputing rolling-window FC metrics...")
    metrics = compare_fc(FC_emp, FC_reps_harm, FC_reps_charm)

    # 5. Plot
    print("\nGenerating plots...")
    plot_results(metrics, OUTPUT_DIR)

    # 6. Save — matching FCmodel.m keys
    out_path = f'{OUTPUT_DIR}/results_fc_model.mat'
    sio.savemat(out_path, {
        'FCemp':   FC_emp,
        'FCsim2':  FC_reps_harm,
        'FCsimC2': FC_reps_charm,
    })
    print(f"  Saved: {out_path}")
    print("\nDone.")


if __name__ == "__main__":
    main()
